# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image_field',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
