# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0002_auto_20180207_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
