# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0008_auto_20181123_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='am',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='bm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='cm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='dm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='em',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='fm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='gm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='xm',
            field=models.IntegerField(null=True),
        ),
    ]
